### ISSUE TITLE
License is in violation.

### ISSUE THREAD

**Issue by crayfishx** [benwtr/hiera-http-eyaml#1]
Hi @benwtr 

I am the maintainer of the origin hiera-http library that this project is forked from and I see that this project is mostly derived from the original code of hiera-http 2.0.  I am a great supporter of open source and what it stands for, and I am very glad that you found the hiera-http code useful and were able to build on it to produce a new project.  The freedom to fork someones work, modify it and release something new is what makes open source so great, so please do not think for one moment I don't fully support this.

Licenses are the cornerstone of a successful open source eco-system,  they are what makes it possible to write, modify and fork software the way that we do.  They ensure that original authors are properly attributed for their own copyrighted code whilst giving the open source community the freedom to innovate and produce fantastic software.  However this system only works when people operate within the (generous) terms of the license they are deriving work from.   This is something that I feel quite passionately about, as I think anyone who appreciates the value of the open source movement should.    Licenses are not just some legal jargon we drop into a repo to get a GitHub icon, they have meaning, and they are important.

Hiera-http was released under the Apache 2.0 license (https://github.com/crayfishx/hiera-http/blob/2.0.0/LICENSE),  this gives you full rights to fork it, modify it and release your own derivative work from it - and once again, I'm very glad you have - however in doing so you must follow the basic terms of the license you derived the work from - namely to retain original copyright notices and to release original code under the same license.

In this instance your hiera-http-eyaml project which is largely derived from an Apache 2.0 licensed fork which has been removed and has been released under the MIT license and copyrighted to you.   This is simply not how it works.  Whilst you are free to license your own additions under MIT, you must still maintain the licenses and attribution for the works derived from the Apache 2.0 licensed project, and this has not been done.

I do appreciate that you have made an attempt to credit the original projects of both hiera-eyaml and hiera-http in your README, and I do not think that you had any malicious intent in stripping out the original license, but I do think this is a very important issue for anyone in open source which is why I'm raising with you.

I hope your project is a success, and I'm glad you found the hiera-http code useful in producing it - but please fix the licensing issues noted.

Regards
Craig

**Comment by ggeldenhuis** [comment]
+ ∞

**Comment by benwtr** [comment]
Hello @crayfishx and thank you for taking the time to craft your explanation.

I apologize fully. To be honest I hadn't really given the license any thought, or open-source licenses much thought in general (besides preferring BSD over GPL.)  Probably because it's never been an issue that has affected me directly, probably I should be taking licenses a little more seriously.

This happened entirely out of my laziness and lack of any strong opinions about open-source licenses. It was _easier_ to copypaste into a new repo than it was to fork, and I probably just accepted the default license when I did so.

I've never taken sharing my own code very seriously. For me, publishing "open-source" is basically: _I glued some bits together and made a stupid thing that solves a problem I had, I'm going to stick it on GitHub so I can find it later and if other people find it useful, cool, now they don't have to write it themselves._ 

Anyway, thank you for your code, it is tremendously useful.

I'd like to fix this immediately. I'll swap out the license and I'll open a PR about attributing the original author that I'd like your feedback on.

**Comment by crayfishx** [comment]
Thanks @benwtr for your candid response.   I figured it was something like this, but thanks for explaining - the PR you raised in #2 is unnecessary, you've already fixed the license back to an Apache 2.0 and all that's needed is #3 

Thanks again for dealing with the issue, and for your understanding.

Regards
Craig

**Comment by benwtr** [comment]
👍
